apiVersion: v1
kind: Namespace
metadata:
  name: vend-vnet
  labels:
    name: vend-vnet

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: vend-vnet
  name: vend-vnet
  labels:
    app: vend-vnet
spec:
  selector:
    matchLabels:
      app: vend-vnet
  template:
    metadata:
      labels:
        app: vend-vnet
    spec:
      hostNetwork: true
      containers:
        - name: vend-vnet
          image: saichler/vendmachine-vnet:latest
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: hdata
              mountPath: /data
      volumes:
        - name: hdata
          hostPath:
            path: /data
            type: DirectoryOrCreate
